name: spangy
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/spalsh_screen_fill.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectfill

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Bold.ttf
  #        - asset: assets/fonts/Roboto_Regular.ttf

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
